export const PAY_AS_YOU_GO_CREDITS = 10;
export const PAY_AS_YOU_GO_PRICE_USD_CENTS = 999;
export const PROFESSIONAL_MONTHLY_PRICE_USD_CENTS = 1990;

export const PAY_AS_YOU_GO_DISPLAY_PRICE = "$9.99";
export const PROFESSIONAL_MONTHLY_DISPLAY_PRICE = "$19.90";
