export const PAY_AS_YOU_GO_CREDITS = 1;
export const PAY_AS_YOU_GO_PRICE_USD_CENTS = 99;
export const PROFESSIONAL_MONTHLY_PRICE_USD_CENTS = 1999;

export const PAY_AS_YOU_GO_DISPLAY_PRICE = "$0.99";
export const PROFESSIONAL_MONTHLY_DISPLAY_PRICE = "$19.99";
