import type { Locale } from "@/i18n/routing";

const copy = {
  en: {
    title: "Keep this photo in higher quality",
    description: "Create a new version from your original photo, with up to 2K images and 720p video where available. AI results may vary from this preview.",
    buy: "Create an HD version — $4.99 / 10 credits",
    terms: "One-time purchase. No subscription. Credits valid for 1 year. Each new version uses 1 credit.",
    open: "Open your HD version — no extra credit",
    create: "Create HD version — 1 credit",
    professionalCreate: "Create HD version",
    creating: "Preparing your HD version…",
    failed: "We could not start the HD version. Please try again. Retrying will not charge twice.",
    notAvailable: "This photo is no longer available for an HD version.",
    keep: "Your current result remains available. An HD remake is a separate generation.",
    quotaTitle: "Continue with this photo",
    quotaBody: "Your credits are used up or unavailable. Buy a pack to continue with the photo you already uploaded.",
    buyCredits: "Buy credits — from $4.99",
    tomorrow: "Processing requires a one-photo purchase or an existing paid allowance.",
    savedTitle: "Your uploaded photo is ready",
    savedBody: "Continue with your uploaded photo. Existing credits or plan benefits apply; otherwise, payment is required before processing.",
    continue: "Continue with this photo",
    dismiss: "Choose another photo",
  },
  zh: {
    title: "把这张照片制作成高清版",
    description: "使用原图重新制作，图片最高 2K，动画最高 720p（视处理类型而定）。AI 重新生成的细节可能与当前预览不同。",
    buy: "制作高清版 — $4.99 / 10 积分",
    terms: "一次购买，不自动续费。积分有效期一年，每次重新制作消耗 1 积分。",
    open: "查看已制作的高清版 — 不再扣积分",
    create: "制作高清版 — 1 积分",
    professionalCreate: "制作高清版",
    creating: "正在准备高清版…",
    failed: "暂时无法开始高清制作，请重试。重复点击不会重复扣费。",
    notAvailable: "这张照片已无法用于高清制作。",
    keep: "当前结果仍然保留，高清重制是另一次生成。",
    quotaTitle: "继续处理这张照片",
    quotaBody: "积分已用完或不可用。购买积分包后，可继续处理刚才上传的照片。",
    buyCredits: "购买积分 — $4.99 起",
    tomorrow: "照片处理需要单张购买或已有付费权益。",
    savedTitle: "已保留刚才上传的照片",
    savedBody: "可继续使用已上传的照片。已有积分或套餐权益仍可使用，否则需先付款再处理。",
    continue: "继续处理这张照片",
    dismiss: "选择另一张照片",
  },
  es: {
    title: "Conserva esta foto con mayor calidad",
    description: "Crea una nueva versión desde tu foto original, con imágenes de hasta 2K y vídeo de 720p según el proceso. El resultado puede variar respecto a esta vista previa.",
    buy: "Crear versión HD — 4,99 US$ / 10 créditos",
    terms: "Pago único, sin suscripción. Créditos válidos por 1 año. Cada nueva versión usa 1 crédito.",
    open: "Abrir tu versión HD — sin otro crédito",
    create: "Crear versión HD — 1 crédito",
    professionalCreate: "Crear versión HD",
    creating: "Preparando tu versión HD…",
    failed: "No se pudo iniciar la versión HD. Inténtalo de nuevo; no se cobrará dos veces.",
    notAvailable: "Esta foto ya no está disponible para crear una versión HD.",
    keep: "Tu resultado actual se conserva. La versión HD es una generación independiente.",
    quotaTitle: "Continúa con esta foto",
    quotaBody: "Tus créditos se agotaron o no están disponibles. Compra un paquete para continuar con la foto que ya subiste.",
    buyCredits: "Comprar créditos — desde 4,99 US$",
    tomorrow: "El procesamiento requiere una compra por foto o créditos disponibles.",
    savedTitle: "Tu foto subida está lista",
    savedBody: "Continúa con tu foto. Usa tus créditos o plan; en caso contrario, paga antes de procesar.",
    continue: "Continuar con esta foto",
    dismiss: "Elegir otra foto",
  },
  ja: {
    title: "この写真を高画質で残す",
    description: "元の写真から新しい版を作成します。処理内容に応じて画像は最大2K、動画は720pです。AIの再生成結果は現在のプレビューと異なる場合があります。",
    buy: "HD版を作成 — $4.99 / 10クレジット",
    terms: "買い切り・自動更新なし。有効期限は1年です。再作成ごとに1クレジットを使用します。",
    open: "HD版を開く — 追加クレジット不要",
    create: "HD版を作成 — 1クレジット",
    professionalCreate: "HD版を作成",
    creating: "HD版を準備しています…",
    failed: "HD版を開始できませんでした。再試行しても二重に消費されません。",
    notAvailable: "この写真からHD版を作成することはできなくなりました。",
    keep: "現在の結果はそのまま残ります。HD版は別の生成です。",
    quotaTitle: "この写真の処理を続ける",
    quotaBody: "クレジットが不足しているか利用できません。パックを購入すると、アップロード済みの写真を処理できます。",
    buyCredits: "クレジットを購入 — $4.99から",
    tomorrow: "処理には写真ごとの購入または有料プランの利用枠が必要です。",
    savedTitle: "アップロード済みの写真があります",
    savedBody: "アップロード済みの写真で続行できます。既存のクレジットやプランを利用するか、処理前にお支払いください。",
    continue: "この写真で続ける",
    dismiss: "別の写真を選ぶ",
  },
} satisfies Record<Locale, Record<string, string>>;

export function getConversionCopy(locale: string) {
  return copy[locale as Locale] ?? copy.en;
}
