import type { Locale } from "@/i18n/routing";
const copy = {
  en: {
    compactSummary: "Same result. No preview watermark. No regeneration.", compactVideo: "Video stays 480p. HD regeneration is separate.", compactImage: "Keeps the generated image resolution.", compactTerms: "One-time payment. No subscription.",
    imageBody: "Unlock the images already created from this photo without the preview watermark. No AI regeneration or increase in resolution.",
    title: "Keep this result", body: "Unlock the images and video already created from this photo, without the preview watermark. No AI regeneration. Video stays at its original 480p resolution; this is not an HD upgrade.", buy: "Unlock this result — $1.99", credit: "Unlock this result — 1 credit", pro: "Unlock this result — included", busy: "Unlocking…", unlocked: "This result is unlocked", unlockedBody: "Download the same result without the preview watermark. Downloading again does not use a credit.", failed: "We could not confirm the unlock yet. Please check this result again before making another purchase.", unavailable: "This result is not available for purchase. Return to your result, or upload a photo and pay before processing.", terms: "One photo’s result, including its generated images and video. One-time payment, no subscription. Does not include another generation.", preview: "View your earlier result", card: "One result", optional: "Optional: create a new HD version", before: "Earlier results keep their original download access. For a new photo, upload and pay $1.99 before processing; the completed result has no watermark. No subscription.", paidBefore: "This generation uses 1 credit and includes downloads. Your existing paid allowance and export quality still apply.", proBefore: "Generation and downloads are included in your Professional plan.", legacy: "Your earlier result keeps its original download access.", checking: "Checking this result…", open: "Open your result", complete: "Payment confirmed — this result is unlocked.", return: "Download this result", same: "Your existing result is ready to download. No new generation or extra credit is needed."
  },
  zh: {
    compactSummary: "同一成品，去除预览水印，不重新生成。", compactVideo: "视频仍为 480p，高清重制另选。", compactImage: "保留当前图片的生成分辨率。", compactTerms: "一次付款，不自动续费。",
    imageBody: "解锁这张原照片本次生成的图片，下载时去除预览水印，不重新生成，也不会提高分辨率。",
    title: "保存这次满意的结果", body: "解锁这张原照片本次生成的图片和视频，下载时去除预览水印，不重新生成。视频保持原来的 480p 分辨率，不会升级为高清。", buy: "解锁当前结果 — $1.99", credit: "解锁当前结果 — 1 积分", pro: "解锁当前结果 — 已包含", busy: "正在解锁…", unlocked: "当前结果已解锁", unlockedBody: "可以下载去除预览水印的同一成品。重复下载不消耗积分。", failed: "暂时无法确认解锁，请稍后重试，确认状态前不要重复购买。", unavailable: "当前结果暂不可购买，请返回结果页；处理新照片需先上传并付款。", terms: "包含一张原照片本次生成的图片和视频。一次付款，不自动续费，不包含重新生成。", preview: "查看历史结果", card: "单次结果", optional: "可选：重新制作高清版", before: "历史结果保留原有下载权益。新照片需上传后先支付 $1.99 再处理，完成后交付无水印结果，无需订阅。", paidBefore: "本次生成消耗 1 积分并包含下载，保留现有付费额度和输出质量权益。", proBefore: "专业版已包含本次生成和下载。", legacy: "历史结果保留原有下载权益。", checking: "正在确认结果…", open: "返回当前结果", complete: "付款已确认，当前结果已解锁。", return: "下载当前结果", same: "可以下载刚才看到的同一成品，无需重新生成或额外消耗积分。"
  },
  es: {
    compactSummary: "El mismo resultado, sin marca de agua ni regeneración.", compactVideo: "El vídeo sigue en 480p. La regeneración HD es aparte.", compactImage: "Conserva la resolución de la imagen generada.", compactTerms: "Pago único. Sin suscripción.",
    imageBody: "Desbloquea las imágenes ya creadas a partir de esta foto sin la marca de agua de la vista previa. No se regeneran ni aumenta su resolución.",
    title: "Conserva este resultado", body: "Desbloquea las imágenes y el vídeo ya creados a partir de esta foto, sin la marca de agua de la vista previa. No se vuelve a generar. El vídeo conserva su resolución original de 480p; no es una mejora a HD.", buy: "Desbloquear este resultado — 1,99 US$", credit: "Desbloquear este resultado — 1 crédito", pro: "Desbloquear este resultado — incluido", busy: "Desbloqueando…", unlocked: "Este resultado está desbloqueado", unlockedBody: "Descarga el mismo resultado sin la marca de agua de la vista previa. Las descargas posteriores no consumen créditos.", failed: "Aún no se pudo confirmar el desbloqueo. Vuelve a comprobar este resultado antes de comprar de nuevo.", unavailable: "Este resultado no está disponible para comprar. Vuelve al resultado o sube una foto y paga antes de procesarla.", terms: "Un resultado de una foto, incluidas sus imágenes y vídeo generados. Pago único, sin suscripción. No incluye otra generación.", preview: "Ver tu resultado anterior", card: "Un resultado", optional: "Opcional: crear una nueva versión HD", before: "Los resultados anteriores conservan su acceso de descarga. Para una nueva foto, sube y paga 1,99 US$ antes del procesamiento; el resultado completo no tiene marca de agua. Sin suscripción.", paidBefore: "Esta generación consume 1 crédito e incluye las descargas. Se mantienen tu cuota de pago y la calidad de exportación.", proBefore: "Tu plan Profesional incluye la generación y las descargas.", legacy: "Tus resultados anteriores conservan su acceso de descarga.", checking: "Comprobando este resultado…", open: "Abrir tu resultado", complete: "Pago confirmado. Este resultado está desbloqueado.", return: "Descargar este resultado", same: "Tu resultado ya está listo para descargar. No requiere otra generación ni otro crédito."
  },
  ja: {
    compactSummary: "同じ仕上がりを透かしなしで。再生成しません。", compactVideo: "動画は480pのまま。HD再生成は別です。", compactImage: "生成済みの画像解像度を保ちます。", compactTerms: "買い切り・自動更新なし。",
    imageBody: "この写真から作成済みの画像を、プレビューの透かしなしでダウンロードできます。AIで再生成せず、解像度も変わりません。",
    title: "この仕上がりを保存", body: "この写真から作成済みの画像と動画を、プレビューの透かしなしでダウンロードできます。AIで再生成しません。動画は元の480pのままで、HDへの変更ではありません。", buy: "この結果を解除 — $1.99", credit: "この結果を解除 — 1クレジット", pro: "この結果を解除 — プランに含まれます", busy: "解除しています…", unlocked: "この結果は解除済みです", unlockedBody: "同じ仕上がりをプレビューの透かしなしでダウンロードできます。再ダウンロードでクレジットは消費しません。", failed: "解除をまだ確認できません。追加購入の前に、この結果をもう一度確認してください。", unavailable: "この結果は購入できません。結果に戻ってください。新しい写真はアップロード後、処理前にお支払いが必要です。", terms: "元写真1枚から今回作成した画像と動画が対象です。買い切り・自動更新なし。再生成は含みません。", preview: "以前の結果を見る", card: "1回の結果", optional: "任意：新しいHD版を作成", before: "以前の結果は従来どおりダウンロードできます。新しい写真はアップロード後、処理前に$1.99のお支払いが必要です。完成した結果は透かしなしで、定期購入ではありません。", paidBefore: "今回の生成は1クレジットを使用し、ダウンロードを含みます。現在の有料枠と出力品質が適用されます。", proBefore: "生成とダウンロードはプロプランに含まれます。", legacy: "以前の結果は従来どおりダウンロードできます。", checking: "結果を確認しています…", open: "結果を開く", complete: "お支払いを確認しました。この結果は解除済みです。", return: "この結果をダウンロード", same: "先ほどの仕上がりをダウンロードできます。再生成や追加クレジットは不要です。"
  },
} satisfies Record<Locale, Record<string, string>>;
export const getDownloadCopy = (locale: string) => copy[locale as Locale] ?? copy.en;
